import { createHash } from 'node:crypto'
import { writeFile, mkdir } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import { catalogue, removedBooks } from '../catalogue/catalogue.mjs'
import { catalogue as legacy } from '../catalogue/legacy-us.mjs'
export function id(key) {
 const h=createHash('sha256').update(`little-piano/catalogue/v1/${key}`).digest('hex')
 return `${h.slice(0,8)}-${h.slice(8,12)}-5${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}`
}
const quote=v=>v===null?'null':typeof v==='number'?String(v):`'${String(v).replaceAll("'","''")}'`
function upsert(table,row,update) {
 return `insert into public.${table} (${Object.keys(row).join(',')}) values (${Object.values(row).map(quote).join(',')}) on conflict(id) do update set ${update.map(k=>`${k}=excluded.${k}`).join(',')};`
}
export function seedSQL(dataset=catalogue) {
 const lines=['-- Generated by npm run seed:generate. Review before applying. Metadata only.','begin;']
 for(const b of dataset) {
  const bookId=id(b.key)
  const row={id:bookId,series:b.series,title:b.title,level:b.level,book_type:b.book_type,edition:b.edition,language:b.language,isbn:b.isbn,catalogue_status:b.catalogue_status,catalogue_active:b.catalogue_active!==false?'true':'false',catalogue_order:b.catalogue_order??1000,catalogue_notes:b.catalogue_notes??null}
  lines.push(upsert('books',row,Object.keys(row).filter(k=>k!=='id')))
  for(const key of b.retired_song_keys??[]) {
   const songId=quote(id(`${b.key}/${key}`))
   // Never silently delete or reassign progress when correcting an edition mismatch.
   lines.push(`do $$ begin if exists(select 1 from public.assessments where song_id=${songId}) then raise exception 'Catalogue correction requires review: an excluded song has assessments'; end if; end $$;`)
   lines.push(`delete from public.catalogue_sources where song_id=${songId};`)
   lines.push(`delete from public.songs where id=${songId};`)
  }
  // Move existing orders above the used range before reordering stable song IDs.
  // This avoids transient unique(book_id,sort_order) collisions on repeat imports.
  lines.push(`update public.songs set sort_order=sort_order+(select coalesce(max(sort_order),0)+1 from public.songs where book_id=${quote(bookId)}) where book_id=${quote(bookId)};`)
  for(const url of b.sources) lines.push(upsert('catalogue_sources',{id:id(`${b.key}/source/${url}`),book_id:bookId,source_url:url,verified_at:b.verified_at},['verified_at']))
  for(const s of b.songs) {
   const songId=id(`${b.key}/${s.key}`)
   lines.push(upsert('songs',{id:songId,book_id:bookId,title:s.title,page_number:s.page_number,sort_order:s.sort_order},['title','page_number','sort_order']))
   lines.push(upsert('catalogue_sources',{id:id(`${b.key}/${s.key}/source/${s.source_url}`),book_id:bookId,song_id:songId,source_url:s.source_url,verified_at:b.verified_at},['verified_at']))
   for(const url of s.additional_sources??[]) lines.push(upsert('catalogue_sources',{id:id(`${b.key}/${s.key}/source/${url}`),book_id:bookId,song_id:songId,source_url:url,verified_at:b.verified_at},['verified_at']))
  }
 }
 if(dataset===catalogue) lines.push(`update public.books set catalogue_active=false where id in (${[...legacy,...removedBooks].map(b=>quote(id(b.key))).join(',')});`)
 return lines.concat('commit;','').join('\n')
}
if(process.argv[1] && import.meta.url===pathToFileURL(process.argv[1]).href) {
 await mkdir('supabase/seeds',{recursive:true})
 await writeFile('supabase/seeds/catalogue.sql',seedSQL())
 console.log(`Generated ${catalogue.length} books and ${catalogue.reduce((n,b)=>n+b.songs.length,0)} song entries. No database contacted.`)
}
