// Metadata only; stable keys define permanent IDs. Never rename imported keys.
const date='2026-09-25'
const au='https://pianoadventures.com.au/'
const qa=l=>`https://pianoadventures.com/piano-books/my-first-piano-adventure/${l}-books/q-and-a/`
const cert='https://pianoadventures.com/wp-content/uploads/sites/13/2017/10/MFPA-Lesson-Book-Award-Certificates.pdf'
const audio='https://pianoadventures.com/online-support-for-piano-adventures-level-4-5-lesson-theory-book-anglicized/'
const rows=(text,source)=>text.split('|').map((entry,i)=>{const [page,title]=entry.split(':');return {key:`entry-${i+1}`,title,page_number:Number(page),sort_order:(i+1)*10,source_url:typeof source==='function'?source(Number(page)):source}})
const notes='Selected verified pieces and named exercises only. Other entries are still missing. Progress covers this list, not the entire printed book.'
function first(l,isbn,text,source){return {key:`my-first-${l}-lesson-en`,series:'My First Piano Adventure',title:`Lesson Book ${l.toUpperCase()}`,level:`Book ${l.toUpperCase()}`,book_type:'Lesson',edition:l==='a'?'English edition (2012+ printing)':'English edition (revision unspecified)',language:'English',isbn,sources:[`https://pianoadventures.com/product/my-first-piano-adventure-lesson-book-${l}/`,source],songs:rows(text,source)}}
function pair(level,type,sku,isbn,text,support=false){const slug=type==='Lesson & Theory'?'lesson-theory':'technique-performance';const source=`${au}publications/piano-adventures-level-${level}-${slug}-book/`;return {key:`all-in-two-${level}-${slug}-anglicised`,series:'Piano Adventures',title:`Level ${level.toUpperCase()} ${type}`,level:`Level ${level.toUpperCase()}`,book_type:type,edition:'All-in-Two Edition (Anglicised)',language:'English (Anglicised)',isbn,sources:[source,...(support?[audio]:[])],songs:rows(text,support?audio:p=>`${au}wp-content/uploads/sites/7/2021/02/${sku}-${level==='4-5'?'':'p'}${String(p).padStart(2,'0')}${level==='3'&&type==='Lesson & Theory'?'-1':''}.jpg`)}}
export const catalogue=[
 first('a','9781616776190','5:Roll Call|10:Will You Play?|12:Stone on the Mountain|14:The Name Game|15:Tiger, Tiger|17:Cookie Dough|20:Twinkle, Twinkle Little Star|23:Monster Bus Driver|28:Kangaroo Show|29:Katie Scores!|30:Tigers at My Door|32:Wendy the Whale|34:Magic Tree House|37:Dancing Feet|38:Cuckoo Clock|40:Dinosaur Music Night|42:Paw Prints|43:Wabbit the Rabbit|44:Little Lost Kitty|47:Band Practice!|48:Monsieur Mouse|50:Raccoon’s Lullaby|54:Mary’s Rockin’ Pets|58:Old-Pig Donald|60:Shepherd, Count Your Sheep|63:Cookie’s Journey|64:Jungle Wedding|66:Riding the Escalator|69:Birthday Train|70:Wish I Were a Fish|72:Oh! I Love Snack Time|74:If You’re Happy|79:Katie’s Dog Tucker|80:Bed on a Boat|82:Eensie Weensie Spider|84:Graduation Party',cert),
 first('b','9781616776213','4:Friends at the Piano|12:Ode to Joy|22:Pumpkin Party|24:Mozart’s Musical Patterns|38:Gallop, Pony|52:On My Two-Wheeler|64:Construction Zone|67:Octave Blues|68:This Is My C Scale|82:Twinkle, Twinkle Little Star',qa('b')),
 first('c','9781616776237','6:Friends at the Piano|8:Con Brio|22:Baby Owl|30:Leap for the Piñata|42:Allegro Skips|46:Night of Stars|48:Falling Elephant|49:Surprise Symphony Theme|50:Bass Clef Chant|54:Mouse in the Clock|56:Bedtime Boogie Woogie|58:You Can Clap for Me|66:All the Raindrops',qa('c')),
 pair('1','Lesson & Theory','IEFF8003EA','9781616776497','8:Firefly|17:Mexican Jumping Beans|31:Mozart’s Five Names|52:Forest Drums'),
 pair('1','Technique & Performance','IEFF8004EA','9781616776510','6:Canoe Ride|11:Legato Etude|15:Above the Pines|34:A Sunny Parade|36:Jumps and Slides|40:Hill and Gully Rider'),
 pair('2a','Lesson & Theory','IEFF8005EA','9781616776527','34:Ode to Joy|56:The Queen’s Royal Entrance'),
 pair('2a','Technique & Performance','IEFF8006EA','9781616776541','14:Hunter’s Chorus|19:The Brave Knight|20:Mr. McGill’s Boop Sha-Bop!|34:The Explorer'),
 pair('2b','Lesson & Theory','IEFF8007EA','9781616776688','14:Spanish Caballero|18:Sixth Hour'),
 pair('2b','Technique & Performance','IEFF8008EA',null,'7:R.H. Brush Stroke|18:Aria (Theme from La Traviata)|20:Jazz Cat Patterns|45:Melody for the Left Hand'),
 pair('3','Lesson & Theory','IEFF8009EA','9781616776862','17:Interval Warm-ups|20:Cossack Ride|62:Tchaikovsky’s Theme'),
 pair('3','Technique & Performance','IEFF8010EA',null,'7:Scale Round-Offs — Five-Note Scoops|32:The Waltz Bass|36:Energico|38:Scale Monster in D|48:Arpeggio Whirl'),
 pair('4-5','Lesson & Theory','IEFF8011EA','9781616776916','5:Soldiers March|6:Medieval Fair|8:Song of India|10:Swing Prelude|16:Distant Bells|18:Sonantina Op36 No1 3rd Mvt|24:Arabesque|26:Andante (Bach Ricci)|30:Ecossaise|32:Volga Boatmen|34:Chanson|40:Pop-Jazz Fantasy|43:Love Song of Kangding|46:Waltz in F|52:Musette in D|54:O Sole Mio|60:Wild Flowers|62:Gigue in A Major|64:Theme from Pastoral Symphony|67:Manhattan Jazz Club|76:Autumn Ballad|80:Risoluto|82:Roses from the South|84:Danse Macabre|87:Minuet in G|88:Minuet in Gm|94:Waltz in Eb|96:Hungarian Dance No 5|101:Wedding March|104:Nocturne|109:The Bear|111:Ballade (Burgmuller)|115:Innocense (Burgmuller)|118:Two-Octave Arpeggios LH|118:Two-Octave Arpeggios RH|120:Waves of the Danube|124:Solfeggieto',true),
 pair('4-5','Technique & Performance','IEFF8012EA','9781616776923','14:Rotation Sprint|14:Chimes in the Mist|18:Arabesque Gesture|18:Adagio Chords|38:D Major Chord Pattern|38:Spring March in D|69:Boléro|72:Arpeggio Flourish No. 1')
].map((b,i)=>({...b,catalogue_status:'partial',verified_at:date,catalogue_active:true,catalogue_order:i+1,catalogue_notes:notes}))
